sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts from gcloud
before_install:
#  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
#  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
#      rm -rf $HOME/google-cloud-sdk;
#      curl https://sdk.cloud.google.com > install.sh;
#      bash install.sh --disable-prompts;
#    fi
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components install kubectl --quiet
#  - gcloud version
#  - gcloud auth activate-service-account --key-file service-account.json
#  - gcloud config set project multi-k8s-387913
#  - gcloud config set compute/zone europe-central2-a
#  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker build -t christiandietrich/docker-react-test -f client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true christiandietrich/docker-react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main

