language: generic
sudo : required
services:
  - docker

before_install: 
  - docker build -t christiandietrich/docker-react-test -f client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true christiandietrich/docker-react-test npm test


after_success: 
  - docker build -t christiandietrich/docker-complex-example-client ./client
  - docker build -t christiandietrich/docker-complex-example-nginx ./nginx
  - docker build -t christiandietrich/docker-complex-example-server ./server
  - docker build -t christiandietrich/docker-complex-example-fibonacci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  # Take those images and push them to docker hub
  - docker push christiandietrich/docker-complex-example-client
  - docker push christiandietrich/docker-complex-example-nginx
  - docker push christiandietrich/docker-complex-example-server
  - docker push christiandietrich/docker-complex-example-fibonacci-worker