version: '3'
services:
  client:
    image: 'christiandietrich/docker-complex-example-client'
    mem_limit: 128m
    hostname: client
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
  redis:
    image: "redis:latest"
  server:
    image: 'christiandietrich/docker-complex-example-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'christiandietrich/docker-complex-example-fibonacci-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'christiandietrich/docker-complex-example-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
